### PR TITLE
Filtering experiments

### PR DESCRIPTION
**Pull request by rhonamackay**
Filters reformatted in models function!

### CODE REVIEW

**Review by faseehahmed1 — APPROVED** [review]
hope no animals were harmed during the experiment

**Review by Suzi-Clark — APPROVED** [review]
FilterWIN experiments

**Review by remiyeku — APPROVED** [review]
Greg is an expert backend reviewer give him rights!!!

**Review by gregrutnam — APPROVED** [review]
Reviewed this backend and i love it

**Pull request merged**
